### PR TITLE
Credits

### PR DESCRIPTION
**Pull request by o-psi**
This pull request adds credits functionality on overpayment or over bulk payment.

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://credits897.pr-review.itflow.org  
 _(automatic message)_

**Comment by johnnyq** [comment]
Nice work @o-psi , although I haven't had a personal need for credits yet this can come in handy for other business utilizing ITFlow and is very much needed, however this really needs to be thoroughly tested especially on how it will affect income reporting and projected income based of the invoice amounts.

**Comment by o-psi** [comment]
We are putting this through its paces now.

**Comment by johnnyq** [comment]
Excellent lets leave it open for a week, the code appears fine

**Comment by johnnyq** [comment]
@o-psi Everything appears to be good, have you guys been using it much on your end and how has your testing been so far with the credits system?

@wrongecho Wanted to check with you to take peek as well, it looks good to me

**Comment by o-psi** [comment]
@johnnyq We haven't had the need to make any credits yet.

**Pull request closed without merging**
