### PR TITLE
Scheduled tickets (appointments)

### PR DESCRIPTION
**Pull request by o-psi**
This pull request includes the following changes:

- Added a new column `ticket_schedule` to the `tickets` table.

- Added a new modal `editTicketScheduleModal` for editing the scheduled time of a ticket.

- Displayed the scheduled time of a ticket in the ticket details section.

- Added a link to edit the scheduled time in the ticket details section.

- Added the tickets to the calendar in the future.

This is seen to be used with appointments in the future, hopefully linking to an external calendar. 
TODO: Send an ical email to add the event to outlook calendars, or sync calendars another way.

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://scheduledtickets867.pr-review.itflow.org  
 _(automatic message)_

**Comment by johnnyq** [comment]
@o-psi We currently already have scheduled tickets (Im sure you already know that), is this different than that or set to replace or merge with it by integrating into one table called tickets?

**Comment by o-psi** [comment]
The current 'scheduled tickets' is better described as 'reoccurring tickets'.

Rather, this is for when a ticket exists, but the work for it is scheduled sometime in the future.

**Comment by o-psi** [comment]
Originally, that is how i thought it would work best aswell, and maybe we can add a link there. But I think we need to rename scheduled tickets to recurring tickets, then it will no longer make sense to have this feature under a Once option. Things do not reoccur once... 

Maybe I can spend some time in the docs explaining it.

**Comment by johnnyq** [comment]
hmmm im almost wondering about merging scheduled (aka recurring tickets into the tickets table and just make it one entity with flags indicating recurring, scheduled or regular ticket.

**Comment by wrongecho** [comment]
What's being proposed here and the existing scheduled/recurring tickets are entirely separate in my view. This is about scheduling a future time to work on a ticket. 

I'd support renaming scheduled tickets to recurring, but perhaps this function should be part of the Pending/On Hold flow instead? 
Tickets would automatically be moved back to an open / working state once the scheduled time arrives. Ideal for planned site visits, new starters, OOH work, etc.

**Comment by o-psi** [comment]
Wrong Echo, perfectly stated. 

I support adding a link on the pending to open this modal when set to pending aswell.

**Comment by o-psi** [comment]
Im gonna get to work on the proposed changes tomorrow.

**Comment by o-psi** [comment]
How do we want to include this into the pending or onhold flow?

**Comment by johnnyq** [comment]
Lets hold off on the pending and on-hold flow for right now and play around with what you got
I reviewed the code Its ready to be reeled in except for the Database changes need to be updated as we recently added AI items to the DB.

**Pull request closed without merging**
