### PR TITLE
Update constructs to not have parenthesis.

### PR DESCRIPTION
**Pull request by o-psi**
This is a biggie, but shoud take care of these intentionality issues:

https://sonarcloud.io/project/issues?resolved=false&id=itflow-org_itflow

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://cleanrequiresandincludes779.pr-review.itflow.org  
 _(automatic message)_

**Comment by o-psi** [comment]
https://sonarcloud.io/project/issues?resolved=false&pullRequest=779&id=itflow-org_itflow 

Success!! Our issues are greatly reduced!

**Comment by johnnyq** [comment]
Something here broke certain javascript functionalities such as TinyMCE Editor, Select2, Copy Function and cannot pin point why or how

**Comment by johnnyq** [comment]
I found the issue it looks like with the mass update it chnaged some things for select2 and daterangepicker which broke included Javascripts below it not to load.
Should be all fixed now.

**Comment by wrongecho** [comment]
This seems to have broken other things. I can't display or copy passwords anymore on the logins page.

**Comment by o-psi** [comment]
By logins, do you mean /client_logins.php?client_id=

I am not able to replicate this.

**Comment by wrongecho** [comment]
> By logins, do you mean /client_logins.php?client_id=
> 
> I am not able to replicate this. @wrongecho

With the latest updates this seems to now be resolved, unsure what exactly happened!

**Pull request merged**
