### PR TITLE
Update to v0.1.2 of TWETech/ITflow

### PR DESCRIPTION
**Pull request by o-psi**
This PR adds more color to the ticket statuses, fixes the assigned to filter for tickets, and adds readable passwords and fixes the accounting disabled option.

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://v012843.pr-review.itflow.org  
 _(automatic message)_

**Comment by wrongecho** [comment]
Test these changes at: https://v012843.pr-review.itflow.org  
 _(automatic message)_

**Comment by o-psi** [comment]
@johnnyq We are now using these numbered revisions on our production environment, so they are being tested much more thoroughly. We are now on v0.1.3

**Comment by johnnyq** [comment]
Fantastic @o-psi , very much appreciated since were hitting stable =]

**Pull request merged**
