### PR TITLE
Enable URL Recovery from logout

### PR DESCRIPTION
**Pull request by ssteeltm**
to acomplish the discussed in https://forum.itflow.org/d/688-session-expire-should-back-with-current-url

When yout get logged out from session expire, it will save last url tried, to when logging again redirect to it.

### CODE REVIEW

**Comment by wrongecho** [comment]
Hey there,

Thanks for the PR!
Been super busy so I haven't had a chance to try this out yet, but I like the idea!

My only issue is that if you put an external link in the URL parameter, it looks like you could potentially divert people to third party websites. This is known as an Open Redirect vulnerability and is generally used in phishing campaigns. 

https://portswigger.net/kb/issues/00500100_open-redirection-reflected

https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html


I'm sure there's a way to mitigate but would love to hear your thoughts?

**Comment by ssteeltm** [comment]
I see now the potential issue.
What if, we just save the uri, since domain we can get from config, and also, we could hash somehow the query parameter

**Comment by wrongecho** [comment]
This looks good to me!

The only thing I could think may be an issue is setting the location based off the `$_SERVER["REQUEST_SCHEME"]`. I know some will be running ITFlow HTTP (as far as the server is concerned) but then using a reverse proxy/tunnel for the HTTPS. What do you think about defaulting that to HTTPS or `//` (which should default to whatever the users browser is connecting with)?

 _(Nitpick: would be fab if you could add a space after the IF statement and include braces for both - it's our standard, even if there's only one line within the statement)_.

Either way @johnnyq I'm happy to get this merged for now and fix forward.

**Review by wrongecho — APPROVED** [review]

**Comment by johnnyq** [comment]
Looks great to me @wrongecho and thank you for the patch @ssteeltm  merging in

**Pull request merged**
