### PR TITLE
Update readme with install script

### PR DESCRIPTION
**Pull request by o-psi**
Updated README.MD to show updated install instructions.

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://Updatereadmewithinstallscript737.pr-review.itflow.org  
 _(automatic message)_

**Comment by wrongecho** [comment]
Hey @o-psi, thanks for the PR!

The install script is definitely the recommended method to install, it's so much quicker than manually installing Apache and cloning everything yourself. I've just made a few small tweaks:

- The security/in development message is already shown further up ("In beta") so doesn't need to be shown again. 

- Moved the security policy link to the top header to make it more visible.

- Combine the download/install commands into one

**Review by wrongecho — APPROVED** [review]
Approved with tweaks

**Comment by o-psi** [comment]
Thanks @wrongecho. I slightly modified the script output the wget as standard output, and pipe into bash directly, avoiding saving the script unless the user actually wants to.

**Review by wrongecho — APPROVED** [review]

**Comment by wrongecho** [comment]
Nice work! Thank you :)

**Pull request merged**
