### PR TITLE
Permissions overhaul - Define permissions in the database

### PR DESCRIPTION
**Pull request by wrongecho**
2nd attempt at this one!
Similar to #1008 but separately defining the roles, modules and associated permissions in the database. Also has admin being a defined role automatically having full access.

Parent issue: #530

-- 

Working OK on PR Review:
image

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://perms21052.pr-review.itflow.org  
 _(automatic message)_

**Comment by wrongecho** [comment]
Test these changes at: https://perms21052.pr-review.itflow.org  
 _(automatic message)_

**Comment by wrongecho** [comment]
Test these changes at: https://perms21052.pr-review.itflow.org  
 _(automatic message)_

**Comment by wrongecho** [comment]
Test these changes at: https://perms21052.pr-review.itflow.org  
 _(automatic message)_

**Comment by wrongecho** [comment]
Test these changes at: https://perms21052.pr-review.itflow.org  
 _(automatic message)_

**Comment by wrongecho** [comment]
Test these changes at: https://perms21052.pr-review.itflow.org  
 _(automatic message)_

**Comment by johnnyq** [comment]
This looks awesome the only thing I would change is the user_role_is_admin from int(11) to tinyint(1).

**Comment by johnnyq** [comment]
I'm going to reel this one in, i'll update the DB field to tinyint later on when I push more updates out today.

**Pull request merged**
