### PR TITLE
Update global search to include client domains

### PR DESCRIPTION
**Pull request by nellistc**
Add domains to global search. Provide domain and domain expiry date in the results. Link to relevant client domains page.

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://globalsearchdomains795.pr-review.itflow.org  
 _(automatic message)_

**Comment by wrongecho** [comment]
Test these changes at: https://globalsearchdomains795.pr-review.itflow.org  
 _(automatic message)_

**Comment by nellistc** [comment]
Thinking about it now, the client should probably be in the search results - if the same domain is listed again multiple clients.

**Comment by johnnyq** [comment]
> Thinking about it now, the client should probably be in the search results - if the same domain is listed against multiple clients. Is that possible?

Typically we do as the domain belongs to a client. So your right a client field should be present.

**Comment by nellistc** [comment]
> Typically we do as the domain belongs to a client. So your right a client field should be present.

Added the relevant client to the results with a link.

**Comment by johnnyq** [comment]
Looks good were gonna merge this one in, thank you @nellistc

**Pull request merged**
