### PR TITLE
show related Files on Asset View

### PR DESCRIPTION
**Pull request by ssteeltm**
initial work on showing related files when in asset view

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://assetviewfiles969.pr-review.itflow.org  
 _(automatic message)_

**Comment by johnnyq** [comment]
Hi @ssteeltm if this is still WIP please convert it Draft, but so far looks good.

**Comment by ssteeltm** [comment]
For first version looks ok, Im trying to make now the view as thumb when file extension permits (like on files view). 
I think this can be merged for now, it at least will list files related

**Comment by johnnyq** [comment]
sounds good @ssteeltm reeling in.

**Pull request merged**
