### PR TITLE
0.1.8.3 (Calendar Update)

### PR DESCRIPTION
**Pull request by o-psi**
Update FullCalendar to 6.1.10, and refactor to improve legibility.

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://0183881.pr-review.itflow.org  
 _(automatic message)_

**Comment by wrongecho** [comment]
Test these changes at: https://0183881.pr-review.itflow.org  
 _(automatic message)_

**Comment by johnnyq** [comment]
nice @o-psi this part really did need some love, but dont foget about the client_events.php as well. LEt me know when this is ready to pull in, im quite excited

**Comment by o-psi** [comment]
@johnnyq good catch, should be good to go!

**Pull request merged**
