### PR TITLE
0.1.8.2 (Scheduled tickets, and Email Improvements)

### PR DESCRIPTION
**Pull request by o-psi**
This is the most up to date version of the scheduled tickets change. Added iCal Functionality via The Zap Cal PHP Library

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://0182875.pr-review.itflow.org  
 _(automatic message)_

**Comment by johnnyq** [comment]
Wow that ical support looks super exciting, I have been wanting something like that, Im gonna review then we'll pull it in

**Comment by johnnyq** [comment]
For the iCal functionality I don't think we need to store it in the DB as a separate field It should just send as an attachment, correct?

**Comment by o-psi** [comment]
I was debating this, but I want the iCal to also show in the mail queue as well eventually, and I don't see that happening easily on the fly any other way.

**Comment by o-psi** [comment]
Also, If the ticket gets rescheduled, a new email needs to be sent to replace the old ICS, this would best be done by comparing when that field changes.

**Comment by johnnyq** [comment]
gotchya that makes sense to me

**Comment by o-psi** [comment]
I am going to work on this a bit more. The emails need some help, and there should be a note in the ticket when scheduled.

**Comment by johnnyq** [comment]
okay sounds good its looking great so far

**Comment by o-psi** [comment]
@johnnyq I think this is ready to go

**Comment by johnnyq** [comment]
looks good, im, reeling in

**Comment by o-psi** [comment]
@johnnyq I would love to write some docs on how this functionality works, yet it seems I do not have perms to create new pages on docs.itflow.com

**Pull request merged**
