### PR TITLE
Sorting Recurring and Quotes

### PR DESCRIPTION
**Pull request by o-psi**
This PR adds sorting for recurring and quotes, in the same manner as https://github.com/itflow-org/itflow/pull/768

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://othersorts769.pr-review.itflow.org  
 _(automatic message)_

**Comment by johnnyq** [comment]
nice! looks like there are some conflicts that need resolved in post/invoice.php
Will pull in once resolved, but other than that it looks great @o-psi

**Comment by o-psi** [comment]
I think I did it!! This git stuff seems needlessly complex haha.

**Comment by johnnyq** [comment]
Hello @o-psi I fixed a few things after we pulled this in, as DB updates was broken this was because tables: quote_items and recurring_items tables do not exist. They all reference just invoice_items.
Also the DB version 0.8.10 did not want to update from 0.8.9 so we changed it to DB Version 0.9.0 and that fixed the issue.
We also dumped the DB Structure for new installs.

**Comment by johnnyq** [comment]
See this git commit for the details
https://github.com/itflow-org/itflow/commit/fba1115b0db40d6a0692f1110b9ce9df229123e7

**Comment by johnnyq** [comment]
Recurring Invoice and Quotes are not displaying the order arrows on recurring or quotes see here

Quote: shows order numbers just no arrows
image

Recurring Invoice: Not showing any sorting arrow button or numbers
image

**Comment by o-psi** [comment]
They are under hamburger menu modals. Planning to do the same to the invoice screen.

**Comment by johnnyq** [comment]
ohhh nice! =] Okay I like that idea! Good work

**Pull request merged**
