### PR TITLE
Refactor client sidebar to improve maintainability

### PR DESCRIPTION
**Pull request by o-psi**
This pull request includes a refactoring of the client sidebar to iterate upon an array, which will improve the maintainability of the codebase, and reduces duplication.

In the future, if we want to change how the sidebar looks, we change it once, and everything updates. Will also be easier to translate to other languages via this method.

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://ClientSideNavRedo838.pr-review.itflow.org  
 _(automatic message)_

**Comment by o-psi** [comment]
image

**Comment by o-psi** [comment]
I would like to do this with the other sidebars. Please let me know what you think @johnnyq.

**Comment by johnnyq** [comment]
Hey this is pretty neat but before we go further here:

Some of the sub menus should remain active for example if you go into contact details. The contact sidebar menu item should stay highlighted, same with document_details

Lets hold off on any major changes here, as I wanted to a do a feature freeze on December 20th and just do bug fixes.

I want to focus on functionality and bugs before the new year for the stable release

**Comment by o-psi** [comment]
What are the bugs we are trying to squash. Is there some sort of test we are running to decide this?

**Comment by johnnyq** [comment]
Yes just manual testing

**Pull request closed without merging**
