### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by r-o-k-u**

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://dev895.pr-review.itflow.org  
 _(automatic message)_

**Comment by wrongecho** [comment]
Hi @r-o-k-u

Could you please share some details about this PR?

**Comment by r-o-k-u** [comment]
Hi, i added the Kenyan currency to the currencies array .

**Comment by wrongecho** [comment]
Hey,

Thanks for clarifying! That's one of the files in the PR - how about the below files?

- .github/workflows/dev_qmanage.yml 

- .github/workflows/master_qmanage.yml

**Review by wrongecho — CHANGES_REQUESTED** [review]
Explanation requested for the YAML files included in this PR.

**Comment by johnnyq** [comment]
@r-o-k-u Can you please explain the Azure YAML File. Were not understanding why they are there

**Pull request closed without merging**
