### PR TITLE
Notifications for technicians in tickets

### PR DESCRIPTION
**Pull request by o-psi**
This pull request refactors the email functionality in the codebase to use the newly created addToMailQueue function. This function centralizes the process of adding emails to the email queue, improving code organization and reducing code duplication.

This was needed to be done IMO before 1.0.

This also fixed the notifications for technicians as mentioned here: https://github.com/itflow-org/itflow/issues/563

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://ticketnotifications835.pr-review.itflow.org  
 _(automatic message)_

**Comment by johnnyq** [comment]
This looks fantastic and was much needed to be done. I like new function.
It looks good but wont know for sure until I pull it in to test further on my local instance.

@o-psi Did you test all or some the mail Functionality with this update by chance?

**Comment by o-psi** [comment]
I tested Invoice, Quotes, reset password, and generate password.

**Comment by johnnyq** [comment]
Merging in we'll test from here but everything looks good

**Pull request merged**
