### PR TITLE
Update Payments to only show Asset Accounts

### PR DESCRIPTION
**Pull request by o-psi**
Update any payment account screen to only show accounts in type group 'assets'.

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://paymentstoassetsaccountsonly777.pr-review.itflow.org  
 _(automatic message)_

**Comment by johnnyq** [comment]
Hey @o-psi Before we get too deep into account types and building reports around them and such.
I haven't had a proper amount of time to review code in depth lately.
But for the Account types I was thinking instead of using ranges for Parent account types for:
Assets
Liabilities
Equity

Create a separate field called account_type_parent_id 1 being assets 2 being liabilities, 3 being equity

Then we can easily query the accounts based on the parent type.

Please let me know your thoughts.

**Comment by o-psi** [comment]
Thats fine by me

**Comment by johnnyq** [comment]
excellent that sounds good, I will take action to update the code Accordingly.

**Comment by johnnyq** [comment]
First Code Commit was pushed out See 
https://github.com/itflow-org/itflow/commit/fcc49c2b40ec1e1b5a39eb5bf2fd32369a225dd7

Ill update the rest to follow the new account_type_parent Structure

**Comment by johnnyq** [comment]
I updated the code base to take advantage of the new account_type_parent field, please let me know if you spot anything that may need changed elsewhere because of this change

**Comment by o-psi** [comment]
Will do!! Nicely done man.

**Pull request merged**
