### PR TITLE
Save ticket timer to local storage

### PR DESCRIPTION
**Pull request by o-psi**
Stores the ticket timer to local storage to make it so that if the ticket is closed, the time is saved.

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://savetimertolocal791.pr-review.itflow.org  
 _(automatic message)_

**Comment by wrongecho** [comment]
This is very neat!

Please ensure to add functionality to clear/reset the timer storage when you submit the ticket, otherwise it just continues the clock with every update.

**Comment by o-psi** [comment]
Good Catch @wrongecho.

@johnnyq any concerns?

**Comment by johnnyq** [comment]
it looks pretty good, although im not 100% familiar with JS either but lets reel it in as I dont see any major issues.

**Pull request merged**
