### PR TITLE
Add timers modal to see all timers

### PR DESCRIPTION
**Pull request by o-psi**
Added a modal to the topnav to see your total timers as suggested here:  https://forum.itflow.org/d/506-new-time-tracking-ui-timer-edits-are-overwrittenreset/5

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://SeeAllTimers803.pr-review.itflow.org  
 _(automatic message)_

**Comment by o-psi** [comment]
@johnnyq this is ready to pull

**Comment by o-psi** [comment]
@johnnyq this has been done

**Comment by wrongecho** [comment]
- Timer should not display when ticketing module is disabled
image


- Closing a ticket does not clear it from the active timers (and once the ticket is closed there is seemingly no easy way to remove this timer at all now)
image


- More general but from a user experience perspective, using the ticket ID in the header is a little confusing. If you re-number the tickets then the database ID here is technically 3 but the ticket ref is TCK-4081 - the view ticket button works as expected though
image


- Again more general, but if there are no timers active then the red notification count should disappear (the way notifications do)
image

**Comment by o-psi** [comment]
@johnnyq @wrongecho  This should be ready

**Comment by johnnyq** [comment]
Hi @o-psi Im looking for over the code and may have missed it but some of the issues @wrongecho pointed out don't seem to be resolved just yet

- Don't display ticket id but ticket number:
- Don't Show Timer if Ticketing module is disabled
- and if the ticket get closed clear the timer for that ticket

**Comment by o-psi** [comment]
@johnnyq all but the first is resolved. I am still trying to think of a good way to get the ticket number out of the ID via JavaScript.

The timer in the header is wrapped in an if, and it's working on my dev environment, so not sure what you know that I don't.

Ticket time does get cleared after close. There is an event listener on the ticket_timer.js file that clears any storage. There is also now a clear all button in the modal to clear stuck or old timers.

**Comment by o-psi** [comment]
Regardless, this exponentially increases the usability of the timers... This is a beta app, correct?

If we are waiting for the feature to be complete, why is there a remember me checkbox on the login screen?

**Comment by johnnyq** [comment]
good point, ill get this finished sometime today and yes it is a beta app, but were trying to hit stable come New Years, just as long as it gets fixed before then. We have so much that needs to get fixed before then. I want to eventually put a feature freeze on ITFlow by the end of November and then just muscle out all the bugs in December.

**Comment by johnnyq** [comment]
and beside that I cant make the DB changes I need for **remember me** because you made DB changes that need merged before I can make DB Changes, but still need reviewed.

**Comment by johnnyq** [comment]
Okay im gonna reel this one in

**Comment by o-psi** [comment]
> and beside that I cant make the DB changes I need for **remember me** because you made DB changes that need merged before I can make DB Changes, but still need reviewed.
@johnnyq I can always redo my DB Update in a PR. Dont let a PR with a DB update get in the way of making this program the best it can be!

**Pull request merged**
