### PR TITLE
Sonar Cleanups

### PR DESCRIPTION
**Pull request by o-psi**
This pull request includes cleanups suggested by Sonar Cloud. It addresses code quality issues and improves the overall maintainability of the codebase.

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://sonarcleanup836.pr-review.itflow.org  
 _(automatic message)_

**Comment by johnnyq** [comment]
Oh this is a big one,ill need time to review it, but im not too keen on what it does with the table columns. Although the code is shorter. Sometimes more code explains the code better. Let remove the table column change for now, and ill continue to review.

**Comment by johnnyq** [comment]
Lets revisit this one after 1.0, right now im in process of heavily testing critical functionality this is going to take me a week or so here. Basically were supposed to be a code freeze on Dec 20th

**Comment by o-psi** [comment]
I was thinking we wanted this done by 1.0, will hold off.

**Pull request closed without merging**
