### PR TITLE
Fixed timezone errors

### PR DESCRIPTION
**Pull request by o-psi**
Fixed the timezone errors seen in the apache log. hopefully this fixes audit log time aswell.

### CODE REVIEW

**Comment by wrongecho** [comment]
Test these changes at: https://fixtimezone764.pr-review.itflow.org  
 _(automatic message)_

**Comment by johnnyq** [comment]
Hey @o-psi Timezone is already in the database under the settings table and its called config_timezone.
Settings table references the company ID in the companies table. Basically all company settings should go in the settings table and all user settings should go in the user_settings table. Keep up the great work. I have been really busy with migrations the last 2 weeks so you came in at the right time, so I should say good timing ;-)

**Comment by o-psi** [comment]
Gotcha, working on a few server migrations right now myself haha
image

**Comment by johnnyq** [comment]
Im going to close this as we already have a var in the DB and fixed via commit by changing setting_timezone to config_timezone 
https://github.com/itflow-org/itflow/commit/33c1e72dcc2c5690f4daae8a755eeacf4f1cd2a2

**Pull request closed without merging**
